### ISSUE TITLE
Shouldn't the timeout use an `AbortSignal` to abort?

### ISSUE THREAD

**Issue by dead-claudia** [Jack-Works/proposal-promise.delay-and-timeout#1]
This would fit more in line with other newer web APIs like `fetch`. Also, it'd work more like `.timeout(ms, {signal})`, not `.timeout(signal, ms)`.

**Comment by dead-claudia** [comment]
I may be misunderstanding the purpose of `warpPromise`, though.

**Comment by Jack-Works** [comment]
see whatwg/html#617 maybe I'm not going to push this to stage 1
